name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('./yarn.lock') }}
      - run: yarn --frozen-lockfile --non-interactive
      - run: yarn lint

  deploy:
    needs: [lint]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startswith(github.ref, 'refs/tags/v') && github.repository_owner == 'fox-one'
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('./yarn.lock') }}
      - name: Setup node env
        uses: actions/setup-node@master
        with:
          node-version: 12.14

      # deploy extension
      - run: yarn --frozen-lockfile --non-interactive
      - run: yarn build
      - run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - run: zip -r "fennec-${RELEASE_TAG}.zip" *
        working-directory: packages/mixin-extension/build

      - name: GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: ${{ env.RELEASE_TAG }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: packages/mixin-extension/build/fennec-${{ env.RELEASE_TAG }}.zip
          asset_name: fennec-${{ env.RELEASE_TAG }}.zip
          asset_content_type: application/zip

      # - name: Upload Chrome Web Store
      #   uses: mnao305/chrome-extension-upload@1.1.1
      #   with:
      #     file-path: fennec-${{ env.RELEASE_TAG }}.zip
      #     extension-id: eincngenkhohbbfpkohipekcmnkfamjp
      #     client-id: ${{ secrets.CLIENT_ID }}
      #     client-secret: ${{ secrets.CLIENT_SECRET }}
      #     refresh-token: ${{ secrets.REFRESH_TOKEN }}

      # deploy demo
      - run: yarn --frozen-lockfile --non-interactive
        working-directory: packages/mixin-extension-demo
      - run: yarn build
        working-directory: packages/mixin-extension-demo
      - run: cp packages/mixin-extension-demo/dist/index.html packages/mixin-extension-demo/dist/404.html
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: zhangqw@fox.one
          build_dir: packages/mixin-extension-demo/dist
