name: Build and deploy to develop.

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'fox-one'
    steps:
      - uses: actions/checkout@master

      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('./yarn.lock') }}

      - name: Setup node env
        uses: actions/setup-node@master
        with:
          node-version: "12"

      - run: yarn --frozen-lockfile --non-interactive

      - run: yarn build

      - name: Zip
        uses: papeloto/action-zip@v1
        with:
          files: ./packages/mixin-extension/build/
          dest: ./packages/mixin-extension/build.zip

      - name: Upload & release
        uses: mnao305/chrome-extension-upload@1.1.1
        with:
          file-path: ./packages/mixin-extension/build.zip
          extension-id: eincngenkhohbbfpkohipekcmnkfamjp
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}

      - name: Upload & release
        uses: Klemensas/chrome-extension-upload-action
        with:
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          file-name: "./packages/mixin-extension/build.zip"
          app-id: "eincngenkhohbbfpkohipekcmnkfamjp"
          publish: true
